import React from "react";
import { Card } from "@/components/ui/card";
import { ScrollText } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen py-12 px-4">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="flex justify-center">
            <div className="relative">
              <div className="absolute inset-0 bg-sky-400 blur-2xl opacity-20 rounded-full" />
              <ScrollText className="w-16 h-16 text-sky-300 relative" />
            </div>
          </div>
          <h1 className="text-5xl md:text-6xl font-bold text-sky-200 scroll-decoration">
            Terms of Service
          </h1>
          <p className="text-xl text-blue-200 italic">
            Last Updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        {/* Terms Content */}
        <Card className="parchment-bg ornate-border p-8 md:p-12 space-y-6">
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-blue-900">Ownership of All Content</h2>
            <div className="text-xs text-gray-700 space-y-2 leading-relaxed">
              <p className="font-semibold text-blue-800">
                Everything created by this application belongs to the creator and owner of the Spirit Story app.
              </p>
              <p>
                By using this application, you acknowledge and agree that:
              </p>
              <ul className="list-disc list-inside pl-2 space-y-1">
                <li>All story analyses generated by the app are owned by the app creator</li>
                <li>All interpretations and spiritual insights produced belong to the app creator</li>
                <li>All character identifications and breakdowns are owned by the app creator</li>
                <li>All content, data, and outputs created through this service become the property of the app creator</li>
              </ul>
            </div>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-blue-900">Your Use of the Service</h2>
            <div className="text-xs text-gray-700 space-y-2 leading-relaxed">
              <p>
                You are granted a limited license to use this application and view the analyses it creates.
              </p>
              <p>
                You may:
              </p>
              <ul className="list-disc list-inside pl-2 space-y-1">
                <li>Use the app to analyze stories for personal viewing</li>
                <li>Read and learn from the spiritual insights provided</li>
                <li>Save analyses in your library for personal reference</li>
              </ul>
              <p className="font-semibold text-blue-800 mt-2">
                You do NOT own the content created by the app, even if you input the source story.
              </p>
            </div>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-blue-900">Intellectual Property Rights</h2>
            <div className="text-xs text-gray-700 space-y-2 leading-relaxed">
              <p>
                The Spirit Story application, including all analyses, interpretations, and generated content, is the intellectual property of the app creator.
              </p>
              <p className="font-semibold text-blue-800">
                The app creator reserves all rights to:
              </p>
              <ul className="list-disc list-inside pl-2 space-y-1">
                <li>Use any analyses created for any purpose</li>
                <li>Share, publish, or distribute content generated by the app</li>
                <li>Modify or improve the content</li>
                <li>Create derivative works from the analyses</li>
              </ul>
            </div>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-blue-900">No Commercial Use by Users</h2>
            <div className="text-xs text-gray-700 space-y-2 leading-relaxed">
              <p>
                Users may not:
              </p>
              <ul className="list-disc list-inside pl-2 space-y-1">
                <li>Sell, license, or commercially exploit any content created by the app</li>
                <li>Claim ownership of analyses or interpretations</li>
                <li>Reproduce or distribute app-generated content without permission</li>
                <li>Use the service to create content for commercial purposes</li>
              </ul>
            </div>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-blue-900">Data Storage</h2>
            <div className="text-xs text-gray-700 space-y-2 leading-relaxed">
              <p>
                Stories and analyses you save in your library are stored for your convenience, but all content remains the property of the app creator.
              </p>
              <p>
                The app creator may:
              </p>
              <ul className="list-disc list-inside pl-2 space-y-1">
                <li>Access all stored analyses</li>
                <li>Use stored content for any purpose</li>
                <li>Modify or remove content at any time</li>
              </ul>
            </div>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-blue-900">The Spirit Story Framework</h2>
            <div className="text-xs text-gray-700 space-y-2 leading-relaxed">
              <p>
                The Spirit Story philosophy, framework, and methodology for analyzing stories through the four classic characters (Mother, Hero, Magician, Monster) is the intellectual property of the app creator.
              </p>
              <p className="font-semibold text-blue-800">
                All applications of this framework through this app are owned by the app creator.
              </p>
            </div>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-blue-900">Changes to Terms</h2>
            <div className="text-xs text-gray-700 space-y-2 leading-relaxed">
              <p>
                These terms may be updated at any time. Your continued use of the app constitutes acceptance of any changes.
              </p>
            </div>
          </section>

          {/* Signature Section */}
          <div className="border-t-4 border-sky-400/30 pt-6 mt-8">
            <div className="text-center space-y-3">
              <p className="text-sm font-bold text-blue-900">
                By using Spirit Story, you agree that all content created by this application is owned by its creator.
              </p>
              <ScrollText className="w-6 h-6 text-sky-400 mx-auto mt-3" />
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}